basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: A secure messaging application
  title: NotWhatsApp API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
